OTP pkg version selection made strict
grisp/grisp_tools pull request #11
Opened 2022-03-11 09:24 UTC by ziopio

This is not a fix but rather a simplification.

I just search a perfect matching version in the available package list.

This is a simpler function in respect to the previous 'find_version'.

If we want to have both: strict selection & minor version search, 
we would need to define a way for the user to specify it in the rebar.config.

2022-03-11 13:30 UTC, ziopio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make it possible to specify an exact OTP version requirement](https://trello.com/c/C7oBc2la/8-make-it-possible-to-specify-an-exact-otp-version-requirement)

2022-03-14 13:07 UTC, eproxus commented
@ziopio We still want both, so we need to retain backwards compatibility with the fuzzy version matching that we have already.

2022-03-14 15:02 UTC, ziopio commented
Ok now we select the perfectly matching version if present.
If not the old method is used.

2022-03-14 15:05 UTC, eproxus commented
@ziopio We need the ability to select e.g. the specific version `23.3` which does not then automatically select the latest `23.3.4.11`. Is this possible with this change?

2022-03-14 15:10 UTC, ziopio commented
@eproxus If you run "grisp deploy" you go into pkg download and you choose only between "23.3.4.9" and "23.3.4.11" so if you write "23.3" you get "23.3.4.11" but if you write "23.4" it does no select anything.

I noticed that if you put a build config the pkg list is full of all OTP options, so something like "23.3" is already present by itself.

2022-03-14 15:12 UTC, ziopio commented
@eproxus  So to actually reply to you... Yes it would select 23.3 if it is listed in the available versions.

2022-03-14 15:15 UTC, ziopio commented
@eproxus Wait do you mean a way to say "23.3 and ONLY that" ?

For this we should instruct the user to write something like "23.3.*" to say "any newer minor subversion is ok if 23.3 is not present"

2022-03-14 16:59 UTC, eproxus commented
@ziopio Exactly! The code already works so that both `"23.3"` and `"23.3.4.11"` selects the same version. What we need (especially for source builds, not package builds) is to be able to say something like `{strict, "23.3"}` (API subject to debate) to select `23.3` when `23.3.X` versions exist.

Another idea would be to use some Rebar/Mix inspired syntax like `"~= 23.3"` or something. Preferably we find a syntax which is backwards compatible with the current behavior (fuzzy matching by default if just a version is given). The Rebar/Hex syntax would allow for this if we interpret `"23.3"` as being prefixed with`~=`.

2022-03-15 13:03 UTC, ziopio commented
Ok now "23.3" -> 23.3.4.11
while "=23.3" -> 23.3

I had to add a regex group and modify some functions to adapt to the new return value.

2022-03-15 13:15 UTC, eproxus commented
@ziopio You're on the right track. I wouldn't modify the regular expression globally (since it is used to parse Git version tags too, where no strict syntax will exist). And we don't need to ship around the strict flag in every parsed version number.

I think we should have a function that parses the `otp_version_requirement` value to first see if it is prefixed with a specifier and only then run the regular expression on the rest. Something like:

```erl
version(#{otp_version_requirement := SVersion} = S0) ->
    ...
    {Type,  {Version, Pre, Build, Full}} = parse_version_requirement(SVersion),
    Indexed = lists:zip(lists:seq(1, length(Version)), Version),
    case find_version({Indexed, Pre, Build, Full}, Type, Versions) of
        ....
    end.
...

parse_version_requirement("=" ++ SVersion) ->
    {match, [RawVersion]} = re:run(SVersion, ?RE_VERSION, ReOpts),
    {strict, RawVersion};
parse_version_requirement(SVersion) ->
    {match, [RawVersion]} = re:run(SVersion, ?RE_VERSION, ReOpts),
    {fuzzy, RawVersion};
```

What do you think?

2022-03-15 13:25 UTC, ziopio commented
Ok I will try this approach

2022-03-15 16:08 UTC, eproxus requested changes

2022-03-15 16:08 UTC, eproxus commented on src/grisp_tools_step.erl
> +    {match, [RawVersion]} = re:run(SVersion, ?RE_VERSION, ReOpts),
There are a few places already where we run this code. I think we should replace it with a function like this:

```
parse_versions(String) ->
    ReOpts = [extended, global, notempty, {capture, all_names, binary}],
    {match, Versions} = re:run(SVersion, ?RE_VERSION, ReOpts),
    Versions.
```

Then you could do like this:

```
    ...
    {Type, [RawVersion]} = parse_version_requirement(SVersion),
    ...

parse_version_requirement("=" ++ SVersion) -> {strict, parse_versions(SVersion)};
parse_version_requirement(SVersion) -> {fuzzy, parse_versions(SVersion)}.
```

2022-03-15 16:08 UTC, eproxus commented on src/grisp_tools_step.erl
> +version_list({Version, Pre, Build, _Full}, N, [Last|_] = List)
I think it is more readable when the functions that are called are defined below the function that calls them. Could you move `find_version_strict/fuzzy` below `find_version`?

2022-03-15 16:55 UTC, ziopio commented on src/grisp_tools_step.erl
> +    {match, [RawVersion]} = re:run(SVersion, ?RE_VERSION, ReOpts),
I trued but I'm not sure if i matched you expectations

2022-03-15 16:55 UTC, ziopio commented on src/grisp_tools_step.erl
> +version_list({Version, Pre, Build, _Full}, N, [Last|_] = List)
done

2022-03-22 13:04 UTC, eproxus approved these changes

2022-03-22 13:06 UTC, merged