Add grisp pack command
grisp/grisp_tools pull request #28
Opened 2024-09-05 16:15 UTC by sylane

2024-09-05 16:15 UTC, sylane commented
The dependency will be fixed when testing and review is done, and I can publish grisp_update_packager

2024-09-06 08:03 UTC, ziopio requested changes
REmember to cross link this PR with its rebar3_grisp sibling

2024-09-06 08:03 UTC, ziopio commented on CHANGELOG.md
> +- Add a pack command to generate a GRiSP 2 software update package: [#27](https://github.com/grisp/grisp_tools/pull/27)
wrong link should be this PR 28

2024-09-06 08:03 UTC, ziopio commented on src/grisp_tools.hrl
> +    "foobar.img",
foobar ? what is this?

2024-09-06 08:03 UTC, ziopio commented on src/grisp_tools.hrl
> +    "barebox-phytec-phycore-imx6ul-emmc-512mb.img"
do we need both of these in for GRiSP2 ?

2024-09-06 08:36 UTC, GwendalLaurent approved these changes

2024-09-06 15:36 UTC, sylane commented on src/grisp_tools.hrl
> +    "barebox-phytec-phycore-imx6ul-emmc-512mb.img"
Not sure if we need both, but the toolchain that is published on the wiki still uses the old boot loader name

2024-09-06 15:37 UTC, sylane commented on src/grisp_tools.hrl
> +    "foobar.img",
Some test boot loader that I forgot to remove, it is fixed.

2024-09-06 15:39 UTC, sylane commented
> REmember to cross link this PR with its rebar3_grisp sibling

@ziopio Do you mean here in the PR description or somewhere else ?

2024-09-06 15:41 UTC, ziopio commented
@sylane cross link the PRs in their description so it is easy to navigate between them and find them in future

2024-09-06 15:52 UTC, ziopio approved these changes

2024-09-06 16:19 UTC, merged